######################################################################
# Automatically generated by qmake (1.07a) Sun Nov 12 22:49:44 2006
######################################################################

TEMPLATE = app
DEPENDPATH += drivers
INCLUDEPATH += .

# Input
HEADERS += depth_dialog.h \
           hdm.h \
           mainWindow.h \
           newpositiondialog.h \
           playerSummary.h \
           position.h \
           positionDialog.h \
           xmlreader.h \
           xmlsqlmap.h
SOURCES += depth_dialog.cpp \
           hdm.cpp \
           main.cpp \
           mainWindow.cpp \
           newpositiondialog.cpp \
           playerSummary.cpp \
           position.cpp \
           positionDialog.cpp \
           xmlreader.cpp \
           xmlsqlmap.cpp \
           drivers/parse_test.cpp \
           drivers/xmlsqlmap_driver.cpp
